In [4]:
# This notebook expects that Modin and Ray are installed, e.g. by `pip install modin[ray]`.
# For all ways to install Modin see official documentation at:
# https://modin.readthedocs.io/en/latest/installation.html
%load_ext autoreload
%autoreload 2
# %aimport modin.pandas
# %aimport qgrid

import modin.pandas as pd
import pandas as pd2
# import qgrid
# from qgrid import QgridWidget
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
import modin.pandas as pd
class MyObject(object):
    def __init__(self, obj):
        self.obj = obj

df = pd.DataFrame({MyObject(None): [1,2]}, index=[MyObject(None),MyObject(None)])
# df = pd.DataFrame({MyObject(None): [1,2]})
print(df)

UserWarning: Distributing <class 'dict'> object. This may take some time.

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 0 do not match.

In [6]:
import modin.pandas as pd
class MyObject(object):
    def __init__(self, obj):
        self.obj = obj

# my_object_vals = [MyObject(MyObject(None)), MyObject(None)]
df = pd.DataFrame({"a": [1,2]}, index=[MyObject(None),MyObject(None)])

In [7]:
df = pd.DataFrame({"a": [1,2,], "b":[MyObject(None),MyObject(None)]})
print(df)
df.set_index("b")
print(df)

   a                                          b
0  1  <__main__.MyObject object at 0x3730a38e0>
1  2  <__main__.MyObject object at 0x3730a3dc0>
   a                                          b
0  1  <__main__.MyObject object at 0x3730a3e50>
1  2  <__main__.MyObject object at 0x3731b0340>

In [8]:
df = pd.DataFrame(
        {
            "A": 1.0,
            "Date": pd.Timestamp("20130102"),
            "C": pd.Series([1,2,3,4], index=list(range(4)), dtype="float32"),
            "D": np.array([3] * 4, dtype="int32"),
            "E": pd.Categorical(["test", "train", "foo", "bar"]),
            "F": ["foo", "bar", "buzz", "fox"],
        }
    )
df.set_index("Date", inplace=True)
view = QgridWidget(df=df)
display(view)
# view._handle_qgrid_msg_helper(
#     {
#         "type": "change_filter",
#         "field": "A",
#         "filter_info": {
#             "field": "A",
#             "type": "slider",
#             "min": 2,
#             "max": 3,
#         },
#     }
# )

UserWarning: Distributing <class 'list'> object. This may take some time.
UserWarning: Distributing <class 'dict'> object. This may take some time.

NameError: name 'QgridWidget' is not defined

In [9]:
# df = pd.DataFrame(columns = ['hello'])
import modin.pandas as pd
print(pd.__version__)

df = pd.DataFrame()
df.iloc[0:100]

0.8.2

UserWarning: Distributing <class 'NoneType'> object. This may take some time.

ValueError: Invalid integer data type 'f'.

In [11]:
df = pd2.DataFrame(columns = ['hello']) 
print(df)
df = df.iloc[0:100]
print(df)

Empty DataFrame
Columns: [hello]
Index: []
Empty DataFrame
Columns: [hello]
Index: []

In [1]:
# This notebook expects that Modin and Ray are installed, e.g. by `pip install modin[ray]`.
# For all ways to install Modin see official documentation at:
# https://modin.readthedocs.io/en/latest/installation.html
%load_ext autoreload
%autoreload 2
# %aimport modin.pandas
# %aimport qgrid

# import modin.pandas as pd
import pandas as pd
import qgrid
from qgrid import QgridWidget
import numpy as np

In [2]:
columns_names = [
        "trip_id", "vendor_id", "pickup_datetime", "dropoff_datetime", "store_and_fwd_flag",
        "rate_code_id", "pickup_longitude", "pickup_latitude", "dropoff_longitude", "dropoff_latitude",
        "passenger_count", "trip_distance", "fare_amount", "extra", "mta_tax", "tip_amount",
        "tolls_amount", "ehail_fee", "improvement_surcharge", "total_amount", "payment_type",
        "trip_type", "pickup", "dropoff", "cab_type", "precipitation", "snow_depth", "snowfall",
        "max_temperature", "min_temperature", "average_wind_speed", "pickup_nyct2010_gid",
        "pickup_ctlabel", "pickup_borocode", "pickup_boroname", "pickup_ct2010",
        "pickup_boroct2010", "pickup_cdeligibil", "pickup_ntacode", "pickup_ntaname", "pickup_puma",
        "dropoff_nyct2010_gid", "dropoff_ctlabel", "dropoff_borocode", "dropoff_boroname",
        "dropoff_ct2010", "dropoff_boroct2010", "dropoff_cdeligibil", "dropoff_ntacode",
        "dropoff_ntaname", "dropoff_puma",
    ]
parse_dates=["pickup_datetime", "dropoff_datetime"]

In [3]:
df = pd.read_csv('https://modin-datasets.s3.amazonaws.com/trips_data.csv', names=columns_names,
                header=None, parse_dates=parse_dates)

In [4]:
df

,trip_id,vendor_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,rate_code_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,...,dropoff_nyct2010_gid,dropoff_ctlabel,dropoff_borocode,dropoff_boroname,dropoff_ct2010,dropoff_boroct2010,dropoff_cdeligibil,dropoff_ntacode,dropoff_ntaname,dropoff_puma
0,1,2,2013-08-01 08:14:37,2013-08-01 09:09:06,N,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,2013-08-01 09:13:00,2013-08-01 11:38:00,N,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2,2013-08-01 09:48:00,2013-08-01 09:49:00,N,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2,2013-08-01 10:38:35,2013-08-01 10:38:51,N,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2,2013-08-01 11:51:45,2013-08-01 12:03:52,N,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9881,2,2013-09-29 01:03:48,2013-09-29 01:09:49,N,1,-73.958336,40.820820,-73.953773,40.825195,...,907.0,225.0,1.0,Manhattan,22500.0,1022500.0,E,MN04,Hamilton Heights,3802.0
9996,9882,2,2013-09-29 03:04:10,2013-09-29 03:09:37,N,1,-73.958824,40.820251,-73.934174,40.853394,...,912.0,271.0,1.0,Manhattan,27100.0,1027100.0,E,MN35,Washington Heights North,3801.0
9997,9883,2,2013-09-30 16:28:12,2013-09-30 16:56:03,N,1,-73.956100,40.818974,-73.941055,40.789993,...,1318.0,170.0,1.0,Manhattan,17000.0,1017000.0,E,MN33,East Harlem South,3804.0
9998,9884,2,2013-09-01 13:15:15,2013-09-01 13:23:10,N,1,-73.955345,40.820053,-73.942444,40.841507,...,911.0,251.0,1.0,Manhattan,25100.0,1025100.0,E,MN36,Washington Heights South,3801.0
9999,9885,2,2013-09-20 07:32:17,2013-09-20 08:01:06,N,1,-73.955353,40.820213,-73.957680,40.765190,...,1758.0,116.0,1.0,Manhattan,11600.0,1011600.0,I,MN31,Lenox Hill-Roosevelt Island,3805.0

In [5]:
small_df = df.iloc[:10, :10]
display(small_df)

,trip_id,vendor_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,rate_code_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
0,1,2,2013-08-01 08:14:37,2013-08-01 09:09:06,N,1,NaN,NaN,NaN,NaN
1,2,2,2013-08-01 09:13:00,2013-08-01 11:38:00,N,1,NaN,NaN,NaN,NaN
2,3,2,2013-08-01 09:48:00,2013-08-01 09:49:00,N,5,NaN,NaN,NaN,NaN
3,4,2,2013-08-01 10:38:35,2013-08-01 10:38:51,N,1,NaN,NaN,NaN,NaN
4,5,2,2013-08-01 11:51:45,2013-08-01 12:03:52,N,1,NaN,NaN,NaN,NaN
5,6,2,2013-08-01 14:33:39,2013-08-01 15:49:00,N,1,NaN,NaN,NaN,NaN
6,7,2,2013-08-01 17:19:00,2013-08-01 17:19:00,N,1,NaN,NaN,NaN,NaN
7,8,2,2013-08-01 17:22:00,2013-08-01 17:22:00,N,1,-73.937767,40.758480,-73.937767,40.758480
8,9,2,2013-08-01 17:24:00,2013-08-01 17:25:00,N,1,-73.937927,40.757843,-73.937927,40.757843
9,10,2,2013-08-01 19:21:09,2013-08-01 19:22:30,N,1,NaN,NaN,NaN,NaN

In [6]:
# Create spreadsheet widget from dataframe
qgrid_widget = qgrid.show_grid(small_df, show_toolbar=True, grid_options={'forceFitColumns': False, 'enableColumnReorder': True})
qgrid_widget

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': False, 'defa…

In [ ]:
# return the resultant dataframe from the filtering, sorting, etc.
qgrid_widget.get_changed_df()

In [ ]:
# qgrid_widget = qgrid.show_grid(small_df._to_pandas(), show_toolbar=True, grid_options={'forceFitColumns': False, 'enableColumnReorder': True})
# qgrid_widget = qgrid.show_grid(small_df, show_toolbar=True, grid_options={'forceFitColumns': False, 'enableColumnReorder': True})
qgrid_widget = qgrid.show_grid(df, show_toolbar=True, grid_options={'forceFitColumns': False, 'enableColumnReorder': True})
qgrid_widget